version: '3.8'

services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5175}:${VITE_PORT:-5173}'
    environment:
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-app

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '33061:3306'  # Host port 33061 mapped to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-app

  postgres-db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: '${DB_POSTGRES_DATABASE}'
      POSTGRES_USER: '${DB_POSTGRES_USERNAME}'
      POSTGRES_PASSWORD: '${DB_POSTGRES_PASSWORD}'
    ports:
      - "54322:5432"  # Host port 54322 mapped to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel-app

  minio:
    image: minio/minio
    restart: always
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - laravel-app

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8026:8025"  # Host port 8026 mapped to MailHog's default port 8025
    networks:
      - laravel-app

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  laravel-app:
    external: true
